ignore:
  - ".github"
  - ".changes"

# Disable all status checks to prevent red X's in CI
# Coverage data is still uploaded and PR comments are still posted
coverage:
  status:
    project: off
    patch: off

comment:
  layout: "header, diff, flags, components" # show component info in the PR comment

component_management:
  individual_components:
    - component_id: unittests
      name: "Unit Tests"
      flag_regexes:
        - "unit"
    - component_id: integrationtests
      name: "Integration Tests"
      flag_regexes:
        - "integration"
