name: "Set up postgres (linux)"
description: "Set up postgres service on linux vm for dbt integration tests"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo apt-get --purge remove postgresql postgresql-*
        sudo apt update -y
        sudo apt install gnupg2 wget vim -y
        sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
        sudo apt update -y
        sudo apt install postgresql-16
        sudo apt-get -y install postgresql postgresql-contrib
        sudo systemctl start postgresql
        sudo systemctl enable postgresql
        pg_isready
        sudo -u postgres bash ${{ github.action_path }}/setup_db.sh
