import decimal
from typing import Any, Optional

class SerializableType: ...
class GenericSerializableType: ...

class SerializationStrategy:
    def serialize(self, value: Any) -> Any: ...
    def deserialize(self, value: Any) -> Any: ...

class RoundedDecimal(SerializationStrategy):
    exp: Any = ...
    rounding: Any = ...
    def __init__(self, places: Optional[Any] = ..., rounding: Optional[Any] = ...) -> None: ...
    def serialize(self, value: Any) -> str: ...
    def deserialize(self, value: str) -> Any: ...
