// DO NOT EDIT!!!
// This file is generated by cargo run --bin adbc-sync

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 410] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "07c3a53a87d2304f37bcb5dedb9596432c5fed8e7f3403dfa9f1d5912e523aa8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "f449484f8fea492855a2d2e8f49ed2b9701c675e6f125b6d54b7b29e1a5bd2fa",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "c408484d21dfcc76f3afbb0be80c353ad276ecebd98f2f66a6cbcf23dccbe6c0",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "7d188d408859741b3cf90dc01e77b2e969b0d98a3c21f83d59efad95df19c0b8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "30caf0f89909ff1bc94a5c30ec4377ffbaed2f82b1c90b314be98688c51932b2",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "2567c010ce8dd660d61ca171ff6ade729dcbf1c71a66be58df7139ce8ff21a4b",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.16"),
        "153a80ed3ff94f19362bb5e7cd556a03fbb64d3a009c7c06b31e8c05a2a5cda8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.17"),
        "d398066b9290ca0564d302a7905e82187680981e0ac603a511d892cf6b31cdd2",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.18"),
        "3750d8c106a37111463157df9ca072e92e66b04161ebcb394e2f40782011fa1c",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.19"),
        "ac77d3d8071e02177febaea811ff290a77bf75fdfee6ed94702bf496afab056a",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.20"),
        "aabc5ea60fec24dc95a55d3dcb8b43f02d4a75616096294e4c9434553458ef8a",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.21"),
        "4b25e29864da4bfe3b27b5695cc1a6b7c6a8b3da01e779cec654a5d6f03a2aba",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.8"),
        "b52f005523f09db5df8e59818f1775364d59086d96f42e0fe79b5a2d13f4d99b",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "ec2d400ed5cc868150aba4d2b995964cc821bb413d697f81bf5e2c358caca31e",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "ba4854112679eaff31303fbdb171827f500f7f9773973804136465ddd5d60507",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "beddb6cea5400630a188a87eb54a0b47d53d2ecf87fbf78c51300f75c6a4bf1a",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "dee60a0169296e524e4e476e27033bd5ef3e738da1f4564b4444b77d1bd4c8fd",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "d099d0e4e36963115ea9fe70b808014eb528bd71a023219240ce02c972f9b27c",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "8e50d0795e4fc4fdddee452c1356f7d213ba32dc1ad9955a746e0c6801a102cf",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "cdf41377abbc56f1c7d6efcd807b37b467c6823b79c1a138fd4305dfd0450fb9",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.16"),
        "4ef95bf4c0ca3c26ffc992091e46a6ff0593eacf8ef27bb608ea43a9d525e2df",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.17"),
        "bf7a70a24875b1e0f5d3830eba9d56d47039877e588201fef894d08792def4d6",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.18"),
        "e8b7c66ea338e645b3585c7e48b89e2ff862af289daa9c03a17879a94fe29ca2",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.19"),
        "40b5e95e812cfb16db0bd8f9a49ed066c305fd981b212a396de283970e1fd515",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.20"),
        "28caef5f5271ab8a59be5bb6bb9553dd0179471b02ba1202a13408c5d85ed5d1",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.21"),
        "7e29847d3b7f3300ace1d243cfa98ffc66b4bbb3f81a044ecd5a2e0173aec3b5",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "346f3a916575f08bdba98d6dd6bc69df5d70d197e614cca25213ec839a4bb1b4",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "7015f7c515997ff666bbe3d96d62dd0da39824177dc9bc69155a989a500eed4d",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "16028dee53e2da1d4bf08b57b39a70ae5334f9923a68e9b047afbc22e7a46f6c",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "107d9dde4e6c081b908b3fa9eda0cc354a7da4a2f062879b91b8110971552fce",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "35d048f8211cbefab956fd677e2767895690881635014fe179ff8548dd95f333",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "ace49003e4e22ca2f65d3c6620464b0f8f8dee5fa035d5eb220de7010f2825ac",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "2da0327e7a3b6072b44df0e59bf7ad00bd61e26d4becd4e3296bb349f4c815a2",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "175d76d9b34bfdf4847fcd4f8eb590260cbf65fa9a09f0ae114a2eac182fa752",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.16"),
        "ac0fa9cf98296bdb8985df84c8bdcf60b8cb9b66cd262a587005dc8b08c30543",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.17"),
        "a5bbd1aa9f61830d0f4a584e43eb8da82854a2879e551566875cd93944baced0",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.18"),
        "d0b8d1f675d2f281b3eed2ab45e9a50523f56e805b75b9c65a82fdaa226f848c",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.19"),
        "69cabb03f881b1233579bf82b6c60e8a3790b2009db497cb7541a8b2e0e0b61f",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.20"),
        "511b08817eeda77506663d4c2d364e00e0aa16baae89667fbbe247fba900ca2a",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.21"),
        "d45fb044d2f9fa5efa04d3f60e6a797e38a00d9ba84c99b0bde89667ed5df473",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.8"),
        "06723a3dc1ff519e952fb9844fd00ee75d414ca79da135207b96bbfd842cfabb",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.9"),
        "288009c1fd5c18ec9a54cfd7c7223179151d3fc57832f77d0c069220cbcc008b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "1e0f6a2db045e217d42e52cc499df1422c81d49c37d7a64704665b4720d04cd0",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "e595ee7b4a84653a74af3a9747ef9f18cfa6c522d514bb10006827ec21ceecf7",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "9fa3d3a0abcf10cff2fe74bf9fe7e1c35ceda27e74fb08d74e52fc815a830383",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "9beec3a1c5ee20147b4511eab7ce787ddb861e540d3c82f900c6dfaa0c9b07a7",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "bc23ddaa0eaeb7dfa9144ab8aad657df64e935e12bb99c5d811f7b21ed411485",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "17740c39df7ff05f0851d19f80e591799f74780309715ecdac289208032bd27d",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.16"),
        "ee830706345e68ee484ee7d4f7dbe830c90b48f2f1fc0832f3fdc47eb09a9d4b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.17"),
        "5949adac13905f7e1efc483df53e690f315ccb6747690a3c042cd98fd89675a4",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.18"),
        "d77f0bb7dc1f0b782a1ed6019b8af8df48bffe53ae6d6dc9cc507511a957222c",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.19"),
        "0d6a526f6fe5d470206929505cee11fd4e836cbda43a435a487edb94a30aa690",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.20"),
        "1a44ffa4f749e4b7ed1fbab6f1e55ddc8acb6eab64201872abb1cdcbec5f72e0",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.21"),
        "22f832ee65bcd9dd6b4c08de908a1d10f5477ed9581f0e8ecaf23c0c6de64991",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "9d1ff67cde78b73bd5cc28b2f5ab4b853c3b4b598d99f7c9f1140b8111bf126b",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "36b9e54aa4ee5df0ebadb66f1635daa9736dc3173794762c09da401b5d9f177f",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "d9c7d501dc590dba12005972af1243797ee97fa717d1bcfe3e971397ed6f002b",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "421ab972c25d7b83bf0a09e0cfb5c91de01454bc7191219662c3dbbe3b876a5c",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "32bc018f9c823c9848a95a251e51d6a39996fb105a62f7a2d6790e51756233a0",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "cab55fdfc3a77fceabbd477b1f82975ab726c2eed8a102700b40a7efe37f56f0",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "0e215e67bb19710ab2b8fe1c5c9a824c6293198f3adfe0aa0ab2a08e1d98f3bd",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "15a7825c0c5c5dd13c5a817a6f5d527815a9b8aa2664c7f90a772a9598bdc671",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.16"),
        "09497a7dc4d37486ec02eb69b9c876cd20836fb354aea7434f3e66711f76bf2b",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.17"),
        "edaa8848d0f54a5a7119fa5ea1d7ecf7aee0c5e68713e28e476812666aaa5981",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.18"),
        "17039f0d395d5f7995da1ec5ca3432b165f9ca00218ec42207709b7b13f6f009",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.19"),
        "0e266cc45d68ccb1706b0794e7484bf33a433ba029d1bbc269efc7c48459eea2",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.20"),
        "69265bc4df88c22f8276ad314d43c6700b7d25727dc3dcbd6817ab7f16acea8e",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.21"),
        "7ab8d6c4c56798da26ebcb9e3cce43ed4f210db6d0ba2ff63553b445712e0d77",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.8"),
        "ecf0127dfcc50f2917fbff4de9022f370b2f1caf44ab75ea01846d4a81990e60",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.9"),
        "4aaf192f26f791ab58850ff357235717245963e9e83401246ac72b54771517a3",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "8127132bad84b9a5635fd67a49d26b0d2a0b4680ed1dd5a18cb46aeec476c1a7",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.1"),
        "5ce77e08d36013e7df934376695ac813761f1966c657fbf5a0146913a9f0ca23",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.2"),
        "743cf5e91c65777d15fedeeb9b505c0c3f2f169add3e25717b09b30697deeaca",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.4"),
        "c558b3ab49c030c5ba15b35f7614cc26cef52545f3dd2fc8c7e94ffbe183a7cf",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.5"),
        "14efdb62924bb6f90c8220a9722344d65e7e5e610a7d02f9805316e93532d0af",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.6"),
        "ca997a6dd32163f4a93a13ceaf71caabb1c49061c4ae252a8ae3bfd2895ae921",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.7"),
        "4d5de411e6b029f753a9f94924c15ee6d9a1169e9ad436132908419c6b2baa32",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.8"),
        "1b42849a1926aaa35c2924e5445b137fd3cccd1a9658b9d392902786d4b62ee5",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "f6f0bb13dac398295b6aa33311a43dcaed6d9963c96bcc3f6cb57dbe81756de0",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "d816b9f8ca51115b313cb1977f64735749addcf2d99f83e4dc27ac2151436e54",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "97daa176420cfef4d9a806eea42e503054235811d09f7195e5a3939948a27709",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.4"),
        "c222e669d4266e4ae576ce7819e6c4d74b00fd2ee9bd95addaabe8d1235ee178",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.5"),
        "b46a328543c403faa931b3142bf9cf47a712bf27740bee6c4becd7234767711d",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.6"),
        "b211ab4c4550d2ef5c9d51fbecb583e9dc88499ce49e6cd95bb54e81f2c678c5",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.7"),
        "3799099c9c8409dcf88a39c48cf87d3275649d4706ed3d93127fc4a2dbf99649",
    ),
    (
        ("bigquery_foundry", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.8"),
        "d4a890d0b731a961d5e32551e2f39afd0a9f391471c964a6cba0738fb68c70f5",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "05f1c1296a5cc5395b53e8ef10a3d653a221b353c4615cc15e0127ee01b42b2e",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.1"),
        "61ef8555654c8ce2209fb7b4a93083a40acb7fa44b89ebe0b649291f0cca0416",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.2"),
        "8eb492eb0fb63a2904ea7174a25074231e11f0650c90777df217e92a6771aff7",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.4"),
        "f9c0bb3ea9ef295167c8dbe7f232068a869481a00122eed758a2cde7e9e3ed44",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.5"),
        "8095b1a6e9fcfc4f66106fc2534a86cc4e86fa671900f03ed452200108be7ef0",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.6"),
        "b771c5eb5d215cbcfcb1b3fa3794e50cd7d9c1da398667dcb35aae09bcbaf2a4",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.7"),
        "f677bb142af97bfa373347868e0551089543c82fea0f67dfbed20bbb41af2777",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.8"),
        "39e47b1e7865454efbab8eb7dd3834faf000bff1be5ff4477624f7026890fd21",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "f9a2c05ab38e1aff74bed11f650c332a7825e23c28db5219bef02101a9e4b4dc",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "f09de4b87f56dc091384b5040e991ab53c553f9977ec7e488c9758273d041697",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "2fef98ce41f955153ac8bcca27c647e2d241150facfdd5e59952286c6d6ee6fe",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.4"),
        "5788a9e126f06dafb0dd7875f3ba040a03fe349324c45d72c9bf0adc09ac136f",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.5"),
        "dbabf4874adbe306117df1cd2ccead5bfcfc2294fc14c34741e62983750b95e1",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.6"),
        "7d0b56d8754818d42f1d8ae3012b78e3cc91f756472345e5a0d1137df02a0847",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.7"),
        "d3e6cc1649a80dcf657ce9b06555d69fe41246036af862e1c3601b6b7b472bdb",
    ),
    (
        ("bigquery_foundry", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.8"),
        "e973689c398cddf987d75f6ed0065344161a5c70015aee5ffd6df9ea13d35861",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "90174bef515a240e3bf0a4a86904013149df9f97d1a12bfc92c0b28431fd26a7",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "cb833ca98e2e62631b86d78044ec42cacfbf9037531dbd882b5778f2b7d81886",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "45dbdd6966be431f3fdf6cdc38f3b15899ea58c98a03f802c3c10776c2c2d7bb",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.4"),
        "c4708cf9602552a15626e564088b5c49150fe118c242c1e62a195e045275c80c",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.5"),
        "5e8467cec71386e78f5af0f45188c1038d4b60224b248dea3ce39ca13b10f0ee",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.6"),
        "35a3c60979001099943a8f0e606d901c2932479107253420991b23e8519353b8",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.7"),
        "53c876015ed42ee5910e19bb19c60796806747d8e41cce047959f27499ea2ccd",
    ),
    (
        ("bigquery_foundry", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.8"),
        "d44508e7b6c5abc5ff47c015021b0fb7ae60643adc21c80d1d8d83f7f9f21c34",
    ),
    (
        ("clickhouse", "apple-darwin", "aarch64", "0.1.0"),
        "0ccd62dbf47dc9714a328e70a1718faad4a188d222170849411829f2339bc5d2",
    ),
    (
        ("clickhouse", "apple-darwin", "aarch64", "0.1.0-alpha.1"),
        "d7f4dd2f67c4ba4e1569986d893ef9a877c3ae385da4ff3aa1faa646adb96f2a",
    ),
    (
        ("clickhouse", "apple-darwin", "aarch64", "0.1.0-alpha.2"),
        "7ba6156458599b35f6a1c5a2ddbc4cd62036c1d2e46abad702bb950478697472",
    ),
    (
        ("clickhouse", "apple-darwin", "aarch64", "0.1.1"),
        "f32488649f24e01dc5b1cb5a724ea50950b4e0b59520b3071ebd6439153e2610",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "aarch64", "0.1.0"),
        "66050b3e1e945cdc9a8c6980e99396aea0592daf37d7e3d28f0ae4eeec2c8f2d",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "aarch64", "0.1.0-alpha.1"),
        "5ea43a9ab39898fb448d23915cbea56c9284afea89d3324501606c3917d3fc37",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "aarch64", "0.1.0-alpha.2"),
        "81cc15fea37bdf211f97be1eafd09d364d1772396a067f314ffbf01a943afec7",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "aarch64", "0.1.1"),
        "509cf895f7ae0c87e70118417798dcb2ef2568eb37293ad7a271aa503bd86b30",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "x86_64", "0.1.0"),
        "6a6805df2b0ffed47beb2c78b4ddd6b2548fe100e42221c9bbcd0999fcae9bd4",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "x86_64", "0.1.0-alpha.1"),
        "ef018d0c80498777583c92403781d8cda934aa5709dd27b624154f18d3891425",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "x86_64", "0.1.0-alpha.2"),
        "d548d9e1e3511553f2e89fe66614e8cb4d69012f194491b869d31cbdbf19343f",
    ),
    (
        ("clickhouse", "manylinux_2_17-linux-gnu", "x86_64", "0.1.1"),
        "4d0d8fb910fd0b792b179b307ab53e3ede3bc051dcf97ecf8c51c04ff8f31bf7",
    ),
    (
        ("clickhouse", "pc-windows-msvc", "x86_64", "0.1.0"),
        "1f92179cc7f154de97edace0c5f1bad016f3dbd4b4b0c4a037401f84114309a7",
    ),
    (
        ("clickhouse", "pc-windows-msvc", "x86_64", "0.1.0-alpha.1"),
        "b29e3234db386be0c6e1cad6e4ea4185944dd063cb34d385b8ba3fca7b5451f2",
    ),
    (
        ("clickhouse", "pc-windows-msvc", "x86_64", "0.1.0-alpha.2"),
        "80a8eeabbb1a2913efc423c1bfddcd99bc5acffc19422181a9f7e8ddec54ed9b",
    ),
    (
        ("clickhouse", "pc-windows-msvc", "x86_64", "0.1.1"),
        "d47397683f6eb486d809d6f29df47e3d3fbbd58d3a377dfba32665bedc353bb1",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.6"),
        "56528db01bce2834d601acb45fe2b6f0ed1e80b7856078fb51f769c1459591ec",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.7"),
        "2aba2e95e2d5110f03bfbacd24a873ff94335f56e09e86ec04453151c499a1b6",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "cc2d50145a4420309c95a65a39b51dc2731279ffe1fa44898462aff7ceda8c3c",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "e9e15cc3dfb74683f753098d25a6e70bc0f5ecb8a4ca0a20ed0bc0db89935506",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "5c05a0cda065fb591bc499c3c10446f94bde32b19f5ffb0ace3145aae058e993",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "e470afdd3ea4c5297510d944309e4ac4770960b2999d85214454568d3308f84d",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.6"),
        "fcc269a403eb936bbf2a26936c7e7c61e8d05370cb087834838ab9eee6a380d4",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.7"),
        "fa06f6e8570f5b5ca65d1d653b157c9fbd8124fc8f3df1f9e1da1ab242deb33f",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "81c6d69d88cfb467c90aa9f16e65548f64ae4c10e8a5c23061a4e9dad9e84021",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "d83af05b478c6e3b0b945ac823bd0edd465a15091060df2f986969516bef9252",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "9467c30b0bafb849290b539aa64c05b21ded13c3eac75e88ea4d75d744c68ef1",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "588f38465ce409cb17f8ff241033baf4a97ed54f23f143a3822b58d292b45478",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.6"),
        "da993d20451662c41c21aea0b878b296532a30fe5d92db34f0ffc7179a6c369c",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.7"),
        "7cdccf45953ad72fc1285d286e52778ece6cb8949d56de43a418f59cde14d858",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "c8744e1a902357f49ee3ef21c6b366334a786af6394790751b0d5b9196857354",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "8d8bc2d435ea7384521c03fe563d46cc609070bae5dcbc090ef4142d2da2b9b7",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "9c93417e4cfb903c9dd045380d41192277c024f323757fa66bc867c3fb194695",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "d72138c9ad8e1cd9a1b739c93ef27201b6072b481b3eee8830af648d4102b30d",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.6"),
        "37a4ba937d9aea99581ebca6b9e418121c4cc81e02f6273d7aa8022121d6854d",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.7"),
        "84e15ef3c5305431d34c84588aba10f4f68d8bbda2adcd157a2d18f39fe71434",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "24846db74ed1b4a9da2535b1215999f700668f8a5e9ccdb3a66ca6822f0175e9",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "50c20e05aedc0fe1cc9325f751953d307a1e743cbac334b27f19f96539e91ba3",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "f74578ced4c2b78194f51f85686725ad935dcdf895c81a142f9f1f3f707558af",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "ec654b492ce6bdeca04d4de20bef67f59ccc39b11a3b8e543e92ac58ae369def",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.6"),
        "e6ec384ae6a106208674f6aa3381baad64207c89da46560a6dfae5ec20d9b9cb",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.7"),
        "5d70ef5a470adf499e8aba40423123ce15df16c050012e16f1511c92091ec712",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "30fdb72ed127c68ec3bf9c0c411eb6e3fa847e670407004612d4c2efdefec37d",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "097926ba6db8df800159cef3ec845ac649d1bf34d8c8d420f6ec98c3022424a7",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "22c1908ae7953f6e39e9110630f89127f267aec048bece33e1d639629c1d806f",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "b8c4f2488ae5ec0a425c5b8b774d85ebc2b281b333befda43d9f3f9dd1153a02",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.0.ga3f6df3"),
        "62fab9c84d894702f9836b51c2bb57672c78813b10ae0fc4d4cac773e8be414d",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.10.g53736d6"),
        "dac715b8fc91769d15098085c63bc740b8b2e3898152344cc55fb81b6d43832f",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.11.gc853a7b"),
        "dc00bbcf22f1811a5fabf087878f59c3415e6a558ce8c6b83426eeb87a1b0851",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.12.gc55396d"),
        "d71943c4a88d7361a55baa726ca6180d3336ab7effe1ccd55b74af95a0095fb8",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.13.g2679dc0"),
        "9d6a67e4bd81850815ef7cbcc3ce321310e96dfb8ddc12f5c59ee65126fc34a9",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.2.gd85701a"),
        "09e99a6d365bd5549cafc35a48e151551938668fdb6988a6df31a0f17d5a2d70",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.3.g55b4a60"),
        "7a19b3f8ba1e49456ae542ecb19ec1ae953aa7e2589973639096af8f9e8c335d",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.4.ge26bfb6"),
        "62fed99ba21262c9dab4999b9a3b474f4db0b13150043dbc09bde719d4b704d2",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.5.ge613996"),
        "8e8a633c11736a02a0bf41640f0b5be36e743c25f2f9fd7ba303086fd7cb3fb2",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.6.gbe8bb7e"),
        "5250eb2eabffe65cc8be40f75c174616ea1fcbab829c466788ac8958c863a2ce",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.7.g9e77239"),
        "6f2ef72fd4097c4610df08b014f7dc268fb5481ae6641433ff0b9414a8ee1532",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.8.g5b803e8"),
        "0904f2bb1b619b680ad2da44c22dacfd75bb671efe9e05709b72c1d127a3a328",
    ),
    (
        ("dbt", "apple-darwin", "aarch64", "0.4.0+dbt0.1.9.g765633c"),
        "f046ddad43c383d302f35a52c2453b91803d32eb2e38f09ee30b60eef3da1cc4",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.0.ga3f6df3"),
        "a71f4dd13d7c5efef55390484d324fa1f3d2127544dc3523326ba63b98ebe31e",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.10.g53736d6"),
        "de9adc5f463eeb447b2a89b0854815be8be12a93783cb6f30cc6543145c09053",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.11.gc853a7b"),
        "7705438c047f1841058b3388daed8a17d0ae0e84dfc602ac351579ed754265de",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.12.gc55396d"),
        "ef0c46beebeed9f3b5b3037ae0c8c0a28b4960ca3014a4b85a73142abf41d296",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.13.g2679dc0"),
        "001efa55df3504d9345009f38ce5127169fa598f7514484c9587ab8ffea8195d",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.2.gd85701a"),
        "fb25a8dbd904717a6fe9a9e4bc8bc1f51087c6495269a408bf76b1d58fdb6973",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.3.g55b4a60"),
        "b8a14b6c4a2a2e10f7d71e60cc498cbf3363a3e25cff6b1584813efa9aff65e7",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.4.ge26bfb6"),
        "f306d827ed9dc4b56693d6edfc7c66d56f10226fe48b97271e612c5981ed4fbb",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.5.ge613996"),
        "7980f36f76402c7ef18442f8fada7d1c0b07a3f049dfd83c618637083cfb33e2",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.6.gbe8bb7e"),
        "823fe8fd634e2a68fe4f7fe0b786083b8be1ed03f37f6d72e551591a5a0c23d9",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.7.g9e77239"),
        "236387f9915a6349785cdac5f3984ca77f9c9a7a684123d399a02a4a8aa1aa7a",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.8.g5b803e8"),
        "a6a36fd8ce5f770cf439d6316c1a05fbf9e1e23440605d7d4a34188dd25ef418",
    ),
    (
        ("dbt", "apple-darwin", "x86_64", "0.4.0+dbt0.1.9.g765633c"),
        "10ee5237371599b37bb715503e90420f041f929942448a420177d5ad151c849c",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.0.ga3f6df3"),
        "1e7a3c6c22ccae07dc726ca9718fbf1966d985bbefc1cf044622081eea26277d",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.10.g53736d6"),
        "23cae36fb7138cf51fefa3fd4ec16b138410909592c73b15a0e29f0c87544457",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.11.gc853a7b"),
        "7de9f8370450d382b7a3f60104d98a050fd4120e3a9f847279b62bc07d016547",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.12.gc55396d"),
        "420627ea3e0600b3b7aaf772dad71936f92550423e488e23f8927213c42614e0",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.13.g2679dc0"),
        "c1a5875ebd89fe354809309579f7c9ed92090e065b5dbaa972ee9abc9d74a5b7",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.2.gd85701a"),
        "0c4eebb307a2bd35d269848e327d5a78aaabcbf0b7938969c39add7c94d02a1f",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.3.g55b4a60"),
        "672ffd0dc4f24da225b1472eb1d36914b7a41e7e4b490fca9ac3e9db24b0ddd6",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.4.ge26bfb6"),
        "d3294ba8fd1a2a157bb4bf1a5c37b46aa8a9f5e3e6c60789d243a6aea92b6d4c",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.5.ge613996"),
        "963fa1c0296514df1ab1d8254451d279e5837e486149fa8f2b16aea5e4e28503",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.6.gbe8bb7e"),
        "79cc55ad945b458cb14ff9b716de7e0622020b16670d1e3e2429b7fabb976467",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.7.g9e77239"),
        "2dffb3163e5eb66347765c6c13467b59f8f6cdd5f41dc0ef5f4aa04a502eb419",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.8.g5b803e8"),
        "319d59dbc88fee9a17c625a32adc16e233df03735782c04a5d0c58e463019cd9",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "aarch64", "0.4.0+dbt0.1.9.g765633c"),
        "6cf97537c2d26954f50ca3c1923a78b81a82fe86ba6f610b145b8df5006c044b",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.0.ga3f6df3"),
        "40373b8e88c457bd9c3b0067868d20c30a09b558a29450d7dfa411346277248d",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.10.g53736d6"),
        "52bd2415de21316995e41356be98eb74abe6aa4b80c3b6a36134133be2b04ab8",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.11.gc853a7b"),
        "cd1027ca81dfab5907eefe0372b9a2fb4704af434e2f1fa9dd035dadd6afb88e",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.12.gc55396d"),
        "f5d149d6179fee5aeec87c40a257a4c8b939264b00c31c580105b352074f2007",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.13.g2679dc0"),
        "2fd78d20bf1cfe93ce917ca8814bc4a5d1a56786d0fbdab4979219add27b1763",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.2.gd85701a"),
        "c0681921eb23ac203d50ffebfde527f46ca8632b9b73b716f4fb67bd65eb31e6",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.3.g55b4a60"),
        "af8e58af9b6d55f10a9ecd5ef22387e551da6b1175497d03b420b1bf3bcc4e65",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.4.ge26bfb6"),
        "9b19a4ec16c2bfe54fa06680f18ea513d6309d973ee7666aa98f29ca075824f3",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.5.ge613996"),
        "35dfdac89494f544d21c2439e3cffb052e93474df775e039206e198019fc8c7c",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.6.gbe8bb7e"),
        "33d04af95e7800120d7bb680d3dd7c33ea4bd8adec38378c4cc3aa8504ef7a39",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.7.g9e77239"),
        "0b5160eae2fd89e2cc2c7f8dc2c109e7d3c5f4bfb7971b4da072b78f83bfb77c",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.8.g5b803e8"),
        "860ba35cf4acca47d359a06de49263d4e326f73b93306adfac4168218ffb2be5",
    ),
    (
        ("dbt", "manylinux_2_28-linux-gnu", "x86_64", "0.4.0+dbt0.1.9.g765633c"),
        "448003266a452c6e3ce4dee339a49e2d29253260c8f932709ed5d809d48a1950",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.0.ga3f6df3"),
        "70a917d2628d2aae9e8eb0a90f83927eaf5d618ec47271427c27ad6715600b7b",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.10.g53736d6"),
        "b03e663196122d353f5790784580ce43cd6f0a29fb9a992d579f98e891dbf9cf",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.11.gc853a7b"),
        "0281e1db06f2b9d6a8a8a768b8d3c2516b6ea34e0b7cc7b3de8c4a0253c7d9d5",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.12.gc55396d"),
        "d0987056bd14ba41690b064b04a6d26f5c7c3279388dcb12d4254401364584ae",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.13.g2679dc0"),
        "1db3fd52604dc42c6e373af2892a04cc06a9a63457e0e27ffbc59d1defc3642a",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.2.gd85701a"),
        "88e91fce4984739e5e63eccfe37d306113443182ee5a51c90ee1c9191c36f792",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.3.g55b4a60"),
        "08f059fa85d43970b50525d40f268c9e5f79373be7fb0c29e879c85237e2ad81",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.4.ge26bfb6"),
        "13789c14e40ea38cbe9be46618b57ebd72e07f083ff065d0c2cf7aa1e3e95ae3",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.5.ge613996"),
        "47bfb77b7de9851968190a96a91409772067a7db75d08ba932a2de982d78e103",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.6.gbe8bb7e"),
        "1a335174ba39ecf6882cbe7c35ea736f0a214b2d46d3dd900cf89fb5ba54ac78",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.7.g9e77239"),
        "c749c73d0053e7dada78ff034e06175a56d1dbbccd2c209793310b0759915fa0",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.8.g5b803e8"),
        "f680376e32f46cb772b6d30cd0df4243efadfc7fe2a0f2760489b13f321a86da",
    ),
    (
        ("dbt", "pc-windows-msvc", "x86_64", "0.4.0+dbt0.1.9.g765633c"),
        "81a591c9db4a707262966da9d37c82bd310b4f71c2fadc341803449d3cfc3256",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.20"),
        "bf6a8920eccb15c8fc53902c52516bf3ef4a988129239e706631e0d59da22053",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "1.5.2"),
        "15a645873704bf5f610eb99cb2f3b8b725914f7172d7037b366e828bd6ae27a5",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "1.5.3"),
        "ac513a8baefc96218fdcdd2a02339e8eec259c44d54a2b2bd8163043262c80fa",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "1.5.4"),
        "0094c4c34218fad716c6d88409d78c90b10a1cbcdb16675989a5ba4db550c95d",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.20"),
        "ba1edff2728f0bd3b81b886baa8841af94a0186954bde69feab3138062f274b7",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "1.5.2"),
        "15a645873704bf5f610eb99cb2f3b8b725914f7172d7037b366e828bd6ae27a5",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "1.5.3"),
        "ac513a8baefc96218fdcdd2a02339e8eec259c44d54a2b2bd8163043262c80fa",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "1.5.4"),
        "0094c4c34218fad716c6d88409d78c90b10a1cbcdb16675989a5ba4db550c95d",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.20"),
        "14d8b6229614670c23cc6711532a22d76aea27b043e296f16c67fc412512fedd",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "1.5.2"),
        "061b4a6014a1456f3e3620328452af3cc687e0067a21d64d0f69dce023c14cce",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "1.5.3"),
        "789999e95798bc845d9948526bdd89ce432959c70702001a05c2aaee6e4b1b24",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "1.5.4"),
        "e50fe3e9c23766f6ccdfc3eb2ca2bf54da83cb639b6f3b3d100a9d83a7c604d9",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.20"),
        "8aad95227a05ecec119f76579625cc61eec52796a4a2e0be877e13b1a7933996",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "1.5.2"),
        "fc875898f6ce25aec77098a10e9160c536701932c7031e862dfcf5b435702852",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "1.5.3"),
        "5dc107adeb7d04ecf085da3d4f08244220ca2670235d66f39ffe80921130c5cb",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "1.5.4"),
        "23528e49435b97f2dfa924f5d19513849937e671bd392696ea26f3457f656556",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.20"),
        "bb36c1f5aeeeb676b722f7c7f5257998b53f113254c20e24937b102caafff658",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "1.5.2"),
        "8df3a965a573fe6fb33e123ae95ecbdf50122a322e968ec60b67f6fa9d182842",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "1.5.3"),
        "73b12943a85219ebc70da1f756fee0d33bbef0aac2a01ae4c6782b4e57f52deb",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "1.5.4"),
        "dd6a975796f513f1a52c0f99a0beecea227e3a4a546724ae63328cb58152aad9",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.26"),
        "8ff984fa575a330e7d95e2950c8c06058b51488774526d49cddc6ca77a61e333",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.27"),
        "1175f573e9a38dedcfb14b2c629a0a558a726720f3f38b464ecb8c74fc424c67",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.28"),
        "48ee92e05c4f702fb07bebec3f2b1a468d9d30e02d9bea10bae717df75bdbd4b",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.29"),
        "aa6adc0db29122a3951e101a10567e828b43e30896c408ed0c60ae040c8e4dd4",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.30"),
        "230bc3911556820e8fe14f1c1f5edf37810350ae6f6faf0c1c8622a5ebea0ff6",
    ),
    (
        ("duckdb_extended", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.0.31"),
        "d393142286e8279d18e0c07d57f0673e619674de8d5d75917933df5adad70b51",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.26"),
        "795c1625f8736cc9cb9122857b44bc8800436800835a64f1a1e7207e614e3806",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.27"),
        "125e08ed1bd7310e4038b308809006d11c8c442e612db069865e1b6e2f6da6ed",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.28"),
        "a58ae356b159d4c0e84a75365f716e81d1b1562ba66a11a554b4bf7ebc6f57a7",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.29"),
        "992481cfe0aaef7be036f7a39ad6472564dcbc9e5c5290265be79a4041262b9f",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.30"),
        "d77bfa8aeb21b78281b52fc3f167fa3251017b80de61d27c81e85fd6441ac6f6",
    ),
    (
        ("duckdb_extended", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.0.31"),
        "580f5eb75f209112fcd2894dba662cb3e34798ca6ed298a3bcfc7f027ba06fcd",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.26"),
        "3f71ca8d73f2379505d25d40ed3e4200fe2eb4827a598cc3f2bb99ca21020931",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.27"),
        "66f8cd705f05695852982332bc8233cf8112b2214150fd54fc6f70ce4ba7281c",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.28"),
        "f68978ec0a45aae650aac66bd4a85897837ae124fc3b826c6009ac46955b66c0",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.29"),
        "1e68f1e6b5b0ce3d6f6bcb239843ff136d6d46bb510ea1cf6fd2c3cb5dc2350a",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.30"),
        "c10cdaac2aea5bae1db1d9f3e0398ea2ee4816e6aeb1589c0d2a0e331423e9b7",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.0.31"),
        "f0ce4722f82fe3b3751451cc67325046c5670a42beea58579b79fdba37441d63",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.26"),
        "5bd6e93cb9a783b5412bcec9b0e0289c1403377a7442ee553ad514654e2fc278",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.27"),
        "dae1405e9b5560a4a371667c3195cdaf25ae95856438697127235fff3a691606",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.28"),
        "7d769ea96c12d1c1c161953f07e7f6f68073dab56cc537b22db07b5a1ce6e0c2",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.29"),
        "d85bb5bdcf3040b8a9c299a5de85163e5e71f3a2036866d8af041c3f253e2560",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.30"),
        "828f28981ec349948c87a159089d6947dbabaa6cfe4e9ab8001c5360398e738e",
    ),
    (
        ("duckdb_extended", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.0.31"),
        "0071c67cb4b0f869d2addadf9195df34fb406909d1d8e5ea35cfa1824af1e837",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.26"),
        "4dd8c879aabdc03949c24206e232dddf6ef0dcffce3d11a5b8a1fe32fdd8637f",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.27"),
        "7e9ffc827d245141807e61ba95650b2d46e76662d31a86ab7d2d1a5d810eae6b",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.28"),
        "9c7fc353caa4a99d8fc3c1a276300cc6a1a87fa15baa8c71c77b2c553b40fbb1",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.29"),
        "7e0d613a2bcac41ac26df55bb61b00ff602ee2fc4a0977e214f3c2a9af4f5453",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.30"),
        "1bbb877d880eddf6ec7c0732baf3d0007efec39f573172687b19b9fca5ec06b0",
    ),
    (
        ("duckdb_extended", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.0.31"),
        "638a94dec702012b9369f6379f00e2675cc730d56feffac4aff4399c45ec9bc2",
    ),
    (
        ("mssql", "apple-darwin", "aarch64", "1.3.1"),
        "7e356f8f2f89a89b7a5c45fc255e8c5429f934b634e6071c689fad323a0f0de4",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "aarch64", "1.3.1"),
        "cb3f81b8a220fb5659f1f9d3516b8cb15742326fb900df01b18cb68bb0dd0e96",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "x86_64", "1.3.1"),
        "8714af2a435e4de896192fa89336dde1461ff127fd1375b07be33a8da4e7da30",
    ),
    (
        ("mssql", "pc-windows-msvc", "x86_64", "1.3.1"),
        "bcb6b0235297c0797e0cd0999fe1cf79d35c6b45e4abf33b9cae0252fc2a8cd3",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "759eaacee1ea8139f884fa258ec8a7496ae9458f66cb8029817a2978b6f651ed",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.21.0+dbt0.21.0"),
        "07afc8277fd952d956b7de7a8129b323dad9a1aea71e35e3a0d31dee6371546d",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "aa0b1da8145aa3b374dd0bd2b52cd02a8814ce3b03490aa8b5fc99178682803c",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.21.0+dbt0.21.0"),
        "cca3bb3f50a93879a346b50fb49374ced4494f65796ccd60e933c841eea3f27f",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "0650e5069c7ba4c545fc2850143109292842b117719991a7554bd35434a08bd0",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.0"),
        "279f5b9f042a7729f33c053e675f6d0c530a9ce8b88fa6965a981bd93a939df8",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "ff3cd85d65c0425eb31471f536812c333dec6ef0eb5e51d537ce607c9d2853dc",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.0"),
        "cbc2a0865bfc311663db2c2564830e4d4d260beda29baecd4371d8ce52eada5b",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "6f38377190af7320b0020c11f726e018cae0932272adba88359bf395c0f8ad94",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.0"),
        "4986f51e67888f77999525301386505f6375edcb36af4018becff374bb3f82e2",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.2"),
        "ab2b73c667a2b977362ca03cdca9ee309c68b1659f428dee176639d9070c9c1c",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.3"),
        "ce4f16d63e73955b7609ce3658fe95a14426ff0394305c1dcff060b5e71ce398",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.4"),
        "06577fa0d7049dbac38ad50c91c13c636f188d3278a2a3abc5ba563eb83d51f2",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.18.5"),
        "2543764be8c60f100a9a5252ea38839c8bb6c9a1bc4abd14ace05c83797fe77e",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.18.6"),
        "57b2f50d385644f28c3f5534cd855f2e3a405ad6aafde068804ab47133a788f0",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.18.7"),
        "abb3d7b74e24af4d4b1d2b2d3d95a4952a504851cb8c2f8e46b19c6b0085f6d8",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.18.8"),
        "3959dc3937994419b917e48113037f5504f2eeb31eb28fda043916c59824a246",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.18.9"),
        "4c6c04d19bfe894260ad7905cbd4b60ea0ddceedbd9d6a529555a646474c58c5",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.2"),
        "4283d97f8adaf6066ee84b9a3efb4ce4340774f8cd77e79310272daa317e9d7f",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.3"),
        "1be66c9643987b70b3baae8e41135415c4433d92e85508bec3c0a3c6e0151978",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.4"),
        "33f49abc1eaebead97d0e3edcfdfa37fb1c92b779bcfa5fee1022bb75ce1c9d4",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.18.5"),
        "6ca69cee28cfae0db39bc207c5d7ed20b040a3b35fdf7ef2fd962163be267e86",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.18.6"),
        "d2d4f8afa1b59b96fe6d755f163e09a9b1320e442ec61b34eeaea4d1146eb134",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.18.7"),
        "c3295f8afb78e673d6e946111d08fc1754ad4dd935bc30e6b2101b339eaaceca",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.18.8"),
        "efd76a9f20f4925d7ef5510863e464efbd71984dd05c41d30c3e015b296fd9d3",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.18.9"),
        "d3dbb28ad13b58c42645feca89180285562c6ecf71ab3025c77cad210ce2da40",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.2"),
        "0ea7538a182b73bbafd4f594f8d63aa2cd26c3c2e354c13967540f861f20ccc7",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.3"),
        "cb2538c84e6dcbad15e074a2a9907a7cab551d66c833264a5af7835a19352cbd",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.4"),
        "4044e6e1f37ef4d5696c56b7de7303f8a56d64678609f2694413baf493cf9560",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.18.5"),
        "564194a3e7766ef2ac67c51325861399367aef1471d8741982f1a665f0080961",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.18.6"),
        "6cf07835a36c0129a8e4541e786a379958b44a599914f8021c77fa4e1b006aad",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.18.7"),
        "f7247b1f868258bda1b7044fcabfb7ac4772848c4ef15e1bbef1f227e697ee7d",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.18.8"),
        "10253e243ade98d17e196261f0bba48906a4bf69a7120c16f37fe9db82c70249",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.18.9"),
        "6dffd1ce9043f72ffde4a15b54c1ff52fe5b8df9d7c76d7017fa27dd01aca72e",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.2"),
        "3c853f6444cd16bb9a7600f6b6350717aac440b840df1790d3c3d138d907283f",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.3"),
        "89c1e7b6b5e860259bb382d2b6257f9c593e8f977365f82dacc17bd14defb533",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.4"),
        "5a2600f85b0f9c8d34d91d8d0ae13cab266947238f97df07efe0351b53af3af9",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.18.5"),
        "0cc48ea7f6f39491750f47f4611ee3debfe8d2a7ed548dad10b6865bd4cfdb75",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.18.6"),
        "e72186195c1aeec1b375a155d0421046665aeadcd26f2c04f70d809f9e4d6b45",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.18.7"),
        "30fb147f88b1e79967d98c9aeb86c0cab630f53e16e7fe9838f77d504cd6b0cd",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.18.8"),
        "fd4afca1bd19c0fdeafd2b8105173a5f3544f6952b104efed020acc3fa7d1ab5",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.18.9"),
        "d081ad2e9a03ef76626785930445c6abd77aae293902f4526bcc088e5c2e9be4",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.2"),
        "3c802b424c2fd1ea7fb45ebd1251fbe3e65b4d53a9d61dd4da303b1d5f206506",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.3"),
        "d6cf68f50f2551e07902d43631ff01f8dd507d9592a43cf8a074ac57ef2cb9e4",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.4"),
        "566dc019803edae2b29a58dace76034a793fd2ace289a54da35438834231e388",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.18.5"),
        "f47931677e3bd3ff10641f9d9ae0143dffefe5e148add30c7cbfd051e371477d",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.18.6"),
        "aa901a4933839e8ebe8563819aef56eca37d0fa9e0ddd95bb609c6716a4731a2",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.18.7"),
        "b83def5ab11552fd1c1b1a683d23cc3a3343c071eeca36fea163ae468b1ea62d",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.18.8"),
        "258ccbc77dbc97be64084ec14f29e5c22d643c4790eba7bc9ee20fe103c141fe",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.18.9"),
        "96a6e86a094001618dc3f680501afa326b6cb90bb58296e319c87b4b07f8e200",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "d18e39ae09ff1a94da2dc3b4af9c7ac5f135d8affe8fab930d21966c6613b234",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0+dbt0.21.1"),
        "a651b99de9f3d4987259735f9d4bd45c965edd76d46f7b8a1126e1ada07257ab",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.2"),
        "7398485ff259430a72b494a0748def1008b73b8f6f8f44a3f8e69e07e595f7e8",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.22.0"),
        "dd1eaf5090467e878316398381000d752a1e59d01856afef5ae516033b0ec73e",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.22.1"),
        "a1b67a3ed75972b231a2af4037e5d21565c821f728004cd9b7a45b63b3d8f166",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "d0b94c4d28569cc95c0a07cb4218b053727ea9df13ed0ef2f55b3a920351d589",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0+dbt0.21.1"),
        "06daae1581f75f8bf4d26fed1baf880d7ef31deeb0e15b5d6e90090e447831cc",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "9bea90938356fde1fd6f45328acc8d4195d65a99d5f0691a0589b22eefc6a5c4",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.22.0"),
        "9676f55baa15ee703447ae13f5e6afaaf2f45e6f59ccbb443b19452017e9d94d",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.22.1"),
        "a80cf5ea730bf9c7e437bd04f613b3bc17cca2b2e3b4c793e40ecf568f83305d",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "a826655fc9b626951d08c39b174756dff99b04b10c33601f9a1feff6325aec7a",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.1"),
        "c77793e9b83963d144a250bcec207dbec598b653eed077f4fae95e59959472c0",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.2"),
        "bc67fe4e18559d9cf32b7a70606062dde549048aeb3891043cfcc359beeeddf6",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.22.0"),
        "d45e958e253e1852ca116d20615889631ffb354c2c1d3b73ed74a30521795589",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.22.1"),
        "b9a9d02b194105aaa45e31e48b8da2331821dd3e22645fce740706655950cca5",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "a1eb2b25f4f4bf63c731fdc5d47bbca621e4bd23c6201b28d6f98ba85e400951",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.1"),
        "6833d78af651a22cd81e8e6b1a67cf5e263ff15cbf116a3292f5558f9cdad696",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "a4164521066952ea7e49429dec0ce416d28504085d1b136e7e1fdb52d1f80c4d",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.22.0"),
        "ecdaf290e104068013c8645578df0c548e1abe32370d03364f31d92accf29fb3",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.22.1"),
        "4d3e17a3afbffb4e22c193c254e5709d4c6006a17fb737ef94063aca4a0c9ec7",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "f73ad9a1bc6f6f418a9abb3ca54723da32f9b70e28b610d772aa796cc4d83641",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.1"),
        "4226fa0ed53848b61647f1bdf5b914bae7a033f44dc5bd84622f6d900c1f32f8",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.2"),
        "62266aef59e70e22ce293a6bc1accd24f09c0eb2283fb24c00bdf6e92213a28d",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.22.0"),
        "315a502177cd6dd0d9ca1d8bc8df44c545f6b1c7da4575300af94e7c4405d299",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.22.1"),
        "4f71b4f0ccdf5823a2fe70e0f8ccd76edcd3abbcae13bbe0fa92e0a8d529179d",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "499ca4757242586134dc5a09d07f6359dfd54ad637b20e497765042c71240708",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "988001635b63ffce5e7ebc5b78aeb4099c4a574a608972789a3a12cc11ec3f98",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "24fb799bcc1211668cdb832c09d3f8e4687f2f789b368f22abc17d7f520871bc",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "c45f3daa5132d929edbba3e1bdd925f21b485c4e3c0e826714d3fcd7bb74e510",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "892ecef4534a9b733b187511703128243ea392711042dff5ea25240f252b6c9f",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "8d9762600543ef7b7136cc00935e518cb750150c7491ee6cc56d894eaf4f7a5f",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.16"),
        "c693bea093be2531745b40d31f703e5cf97237bfa2422718cb9f61b63fa90cd9",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.17"),
        "750dbc2ad44bc3cdaad714bda4e9efaa7436359ad118f5a8645f1581261d5553",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.21.18"),
        "1fced2b2722975394b1d146438c3ebb10027513f25b3c78c5f0eeefd2ed5d28d",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "2373e633158e743e3df33ec7b79816f25c252be936e834a8e49400dd51c9f19e",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "61585acd8b80f3a808cffb1d030312ee995beacb86f9afcbae937ca4ba93d1e1",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "9100012d9dbf968e3346485bc8eb93b8308e174b9e8c0f2ed08a232b1269ae0a",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "889fb9b386b9875c9e54d06982bb475fc15c46ac413c9aa2d58e1711a933ae27",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "c206df97d94d84295c7713f49c48199301d20834489cb276b576d513864f80f4",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "e4b9107d787357c6720a3e1817d9fda9e3eb69d62b31e9339c85540174abb86b",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.16"),
        "4d65fe00a6186a067d1f58d523c6c5bdfc623fc5625fbf03e1ba340fc23c9c1c",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.17"),
        "3730d41c7f83813ab9a04d2ee44ce01abcad5cc28717044aaa1d991b5efab765",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.21.18"),
        "9e4b2e955542bca8676bfe01dc5a00709cc60802d4051517f307884c2bfe54eb",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.10"),
        "a29e533233009fef21bccb93950b338e41806536d84ed5b6b42e657fcafb9999",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.11"),
        "725f717916e5baff2bb9068bc1e0b2b989ea344860bf355038c9a914d4d02ff8",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.12"),
        "38dddea25a7e4ead5d253cf491aebc8db7174bdcb5e2163bd67ae4a0ae426411",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.13"),
        "527a6d8ffc6e7ce2b922a49f21c646d713617f6b1c1bda799800ca9cc7d80407",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.14"),
        "34c1e80710ab2c7fd17a9c415452112341ce2e217bf2d5d1e4371d3860229111",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.15"),
        "9e203377486a63e74102208a3b273071c4c70c705534745bc63214cb79cde04e",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.16"),
        "d9625920784d5a88b0ca7cdbdd346989ed8e865ca6f139aa8c6f07970e21cff8",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.17"),
        "1986c6a1da0d5db8557eb3b3db27a087525227e90332ec5b04c2445132be2658",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.21.18"),
        "2ec2b93d401c0213afd96331dbeef05f2c6a3c511d8c6ac6dee698256e9a282d",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "60212a57ec83687b8db4e5aeddda59b4f472b97518ba34322c4d3e8e64d14172",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "cc4834689ab2ac2c02bcadee0346534d88e5e0e5e1f72a172935d074d17bc130",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "0672a665f36f262f8919554631465d25bdac5e2242f7053254708883013dc295",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "36099516357b357b6b6d07c03b6e6980425671b88b8319bf28e7da5e24df9df8",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "21b0a5e8896e4c4a80aa26822db4acaa7adfb4b7baaf767ac33ce87e8805784a",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "234da040cd3e3196df9a1ecdac7008c3414c1d2aa93682d3fd549be4bbe77048",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.16"),
        "386d86bf8f2c7369a9643ee6881748f5051da493dfce14532203257277d8e75c",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.17"),
        "a6562582599854847e0bb2fe05ffdcadb2d3a09e479e29aca5f026f5e0a16630",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.21.18"),
        "b6aa3c709716f0c512e26a33dd2154f3938e863ba29638817529254679f4a5f9",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.10"),
        "896042c7f2d8ffc82093a79239a1adaa938e436952088fe369b86ccfdd04a79a",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.11"),
        "76a3263906d2d8c723b707584c3ac7de0d7e398d3fd25806e2b03a3541879ff3",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.12"),
        "6ebe6522377d8ebd9af59a51eab3a43fdf3e36c03aa4bf06ea17f914f7f99adc",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.13"),
        "06341a78ee31243b141405949c2d315506a5fc9401b4373f98c70fbefce406c2",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.14"),
        "0b969b0a2443ee52b5b982e2b98a8314a27871b0f0b762518f42585c65f54c73",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.15"),
        "3e8e36b57f6b613df6d6e7e7d1f7a0e886bbe43982b8301b8e97aa5cf0928900",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.16"),
        "3d7d52624f461b527167f0d90a293cf23cdac92b7400eeaaf0176a0fbb64fe16",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.17"),
        "668b8ff33f280440a0da63c40febce13b3da9d8eff8db2b696e0707a55dd7949",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.21.18"),
        "f1a8f8171e3f7ab24ec0384d25898140ea908dc3298cf688196b8b50083fb952",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b6c5434bea75b3a1da5d4f9598de93384d316c44e6fcd21d8b2dd8b3dfad93de",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.1"),
        "bae99943762c0a0ee9bc615b49aff22668ec5cb3d4f3447ebb738abda7d0f0e5",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.2"),
        "c67f0438c19ad463bc9eb0792f504fb14105e6470cde1974651ea30e08abfacb",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "347b18c1cc2fb82a22e3b51cb5d8f1165991cfc5eccf147f1baea3e1ddb7fb67",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "48298834a061ab3809189a6bbab828b502e0fcc3a3a836e90a27e3ed62a7c044",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "70a74705e224a1cd777fbd8453ee3ae631ff7c68bcbbd2a1282cacf49f8e29e6",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b653fd0fe587e46f71375ce6927b81385c706dc80af98b9ab19b82799119f91b",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.1"),
        "7212f821c41131c9bd229875f3546e6a9da26f4a855faf18c8788a447de5b2fa",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.2"),
        "b75b2da9fad45d4762be3df198d647fa5cb268fe9197a0a5d6b8be4e9b429235",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "3712e4d8dd9938c22e070f66bafb7757e67ce8a29c13de57bf17c214013a13dc",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "09f3477242f0a1741954567b39e7bad1493e89b6c82b7f28e73ca2a88645745e",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "396d683d0db0dcd3f8a4eb72981663d32ed45e7d191b4db9f72a0c8615c65897",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "ee8d81104889a3e7a0324e108bc41a0a38e724806b92136e2c38f96e5ee7ca93",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.1"),
        "7530ed9212418205bfa5196b40541ccff8e83137852d2b3c732873abdea9e747",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.2"),
        "2c8185419f355e233fb77b68221bde0b361a5efe9d4bdb14198c56eb1c81aa07",
    ),
];
