[package]
name = "dbt-profile-schemas"
version.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
keywords.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
dbt-adapter-core = { workspace = true }
dbt-common = { workspace = true }
dbt-fusion-workspace-hack = { version = "0.1" }
dbt-schemas = { workspace = true }

dialoguer = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lib]
name = "dbt_profile_schemas"
path = "src/lib.rs"
doctest = false
